### ISSUE TITLE
Need to input password when the system run oamlspot.sh

### ISSUE THREAD

**Issue by nomaddo** [akabe/setup#1]
インストール時にocamlspot.shを実行するときにパスワードの入力が求められる。
インストールをほったらかしに出来ないのでちょっと不便です。

**Comment by akabe** [comment]
sudo がパスワードを要求してくる，ということですか？

**Comment by nomaddo** [comment]
すみません、間違えました。
インストール時にocamlspot.shをcpする際に、パスワードの入力を要求してくると思ったのですが、
再現できなかったです。すみません。

**Comment by akabe** [comment]
sudo はセキュリティ上の理由で，一定時間が経過すると，再度パスワードの入力を要求します．それと勘違いしたのではないでしょうか．もしそうだとすると，たしかに不便ですが，解決策としては，シェルスクリプト自体を su コマンド上で動かすくらいしか無いと思います．su コマンドを使うと，（Emacs の設定ファイルとか）全てのファイルが root 権限で作られてしまって，ユーザ権限で編集できなくなるので不便だと思って，現在の実装では sudo コマンドを使っています（chown や chmod でいちいちパーミッションいじるのも面倒なので）．
