### ISSUE TITLE
Fail to install `flashplugin-nonfree`

### ISSUE THREAD

**Issue by nomaddo** [akabe/setup#3]
sudo apt-get install flashplugin-nonfree が失敗します。

    sudo apt-get install flashplugin-nonfree
    パッケージリストを読み込んでいます... 完了
    依存関係ツリーを作成しています
    状態情報を読み取っています... 完了
    パッケージ flashplugin-nonfree はデータベースには存在しますが、利用できません。
    おそらく、そのパッケいーじが見つからないか、もう古くなっているか、
    あるいは別のソースからのみしか利用できないという状況が考えられます
    
    E: パッケージ'flashplugin-nonfree' にはインストール候補がありません
    [ERROR] Failed with status 100

**Comment by akabe** [comment]
最近脆弱性が見つかったようなので，そのせいかもしれません．
純正のプラグインがなくても，フラッシュを再生できるようです（機能が制限されるようですが）
これについては，pull-request #4 で解決したいと思います（もう少し良い解決策を思いついたら，実装するかもしれません）
